export { default as HomePage } from './HomePage'
export { default as LoginPage } from './LoginPage'
export { default as SignupPage } from './SignupPage'
export { default as ProfilePage } from './Profile'
export { default as PostPage } from './PostPage'
